version: '3.9'

services:
  web_1:
    build: web/.
    depends_on:
      - db
    links:
      - db
      - rabbit
    environment:
      NAME: web_1
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8001:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
  db:
    image: mysql
    restart: always
    build: ./mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DB: laravel
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
  rabbit:
    image: rabbitmq:management
    hostname: rabbit
    build: ./rabbitmq
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: abc
    healthcheck:
      test: ["CMD", "CURL", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
  nginx:
    build: ./nginx
    image: nginx
    ports:
      - "8080:8000"
    depends_on:
      - web_1
    links:
      - web_1
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
  redis:
    image: redis

volumes:
  mysql: